import { AnimationBase } from '../animations.js';

export default class LissajousPendulum extends AnimationBase {
    static metadata = {
        name: {
            en: "Lissajous Pendulum",
            ja: "リサージュ振り子",
            de: "Lissajous-Pendel",
            es: "Péndulo de Lissajous",
            fr: "Pendule de Lissajous",
            pt: "Pêndulo de Lissajous",
            ko: "리사주 진자",
            zh: "利萨茹摆"
        },
        description: {
            en: "Elegant mathematical curves generated by harmonic motion.",
            ja: "調和振動によって描かれる、優雅で数学的なリサージュ曲線です。",
            de: "Elegante mathematische Kurven, die durch harmonische Schwingungen erzeugt werden.",
            es: "Elegantes curvas matemáticas generadas por movimiento armónico.",
            fr: "Élégantes courbes mathématiques générées par un mouvement harmonique.",
            pt: "Curvas matemáticas elegantes geradas por movimento harmônico.",
            ko: "조화 진동에 의해 생성되는 우아하고 수학적인 리사주 곡선입니다.",
            zh: "由谐波运动产生的优雅数学曲线。"
        },
        author: "QuickLog-Solo"
    };
    config = { mode: 'canvas', usePseudoSpace: false };

    setup(width, height) {
        this.width = width;
        this.height = height;
        this.size = Math.min(width, height) * 0.4;
    }

    draw(ctx, { width, height, progress, exclusionAreas }) {
        this.width = width;
        this.height = height;
        this.size = Math.min(width, height) * 0.4;

        let centerX = width / 2;
        let centerY = height / 2;

        if (exclusionAreas && exclusionAreas.length > 0) {
            const margin = this.size + 10;
            const spots = [
                {x: margin, y: margin},
                {x: width - margin, y: margin},
                {x: margin, y: height - margin},
                {x: width - margin, y: height - margin},
                {x: width / 2, y: height / 2}
            ];
            for (const spot of spots) {
                const overlap = exclusionAreas.some(area => {
                    return spot.x + this.size > area.x && spot.x - this.size < area.x + area.width &&
                           spot.y + this.size > area.y && spot.y - this.size < area.y + area.height;
                });
                if (!overlap) {
                    centerX = spot.x;
                    centerY = spot.y;
                    break;
                }
            }
        }

        ctx.strokeStyle = '#fff';
        ctx.lineWidth = 1;
        ctx.globalAlpha = 0.4;

        const a = 3;
        const b = 2 + progress;
        const delta = Math.PI / 2;

        ctx.beginPath();
        for (let t = 0; t < Math.PI * 2; t += 0.05) {
            const x = centerX + this.size * Math.sin(a * t + delta);
            const y = centerY + this.size * Math.sin(b * t);
            if (t === 0) ctx.moveTo(x, y);
            else ctx.lineTo(x, y);
        }
        ctx.stroke();

        const now = Date.now() / 1000;
        const tx = centerX + this.size * Math.sin(a * now + delta);
        const ty = centerY + this.size * Math.sin(b * now);
        ctx.beginPath();
        ctx.arc(tx, ty, 4, 0, Math.PI * 2);
        ctx.fillStyle = '#fff';
        ctx.globalAlpha = 1.0;
        ctx.fill();
    }
}
