import { test, expect } from '@playwright/test';

test.describe('Maintenance and Initialization', () => {
    test.beforeEach(async ({ page }) => {
        const dbName = `MaintenanceDB_${Math.random().toString(36).substring(7)}`;
        await page.goto(`/projects/app/app.html?lang=ja&db=${dbName}`);
        await page.waitForSelector('.category-btn');
    });

    test('should clear all logs', async ({ page }) => {
        // 1. Verify logs exist (dummy data is generated by default)
        const initialCount = await page.locator('.log-item').count();
        expect(initialCount).toBeGreaterThan(0);

        // 2. Clear logs via maintenance
        await page.click('#settings-toggle');
        await page.click('button[data-tab="maintenance"]');

        await page.click('#clear-logs-btn');
        await page.click('#confirm-ok-btn');

        // 3. Verify logs are gone
        await page.click('.close-btn');
        await expect(page.locator('.log-item')).toHaveCount(0);
    });

    test('should reset settings only', async ({ page }) => {
        // 1. Change a setting (e.g., theme to dark)
        await page.click('#settings-toggle');
        await page.selectOption('#theme-select', 'dark');
        await expect(page.locator('body')).toHaveClass(/theme-dark/);

        // 2. Add a custom category to ensure it's NOT deleted
        await page.click('button[data-tab="categories"]');
        await page.locator('#new-category-name-settings').fill('KeepMe');
        await page.click('#add-category-btn-settings');
        await expect(page.locator('.category-edit-name[value="KeepMe"]')).toBeVisible();

        // 3. Reset settings
        await page.click('button[data-tab="maintenance"]');
        await page.click('#reset-settings-btn');
        await page.click('#confirm-ok-btn');

        // Page reloads after reset
        await page.waitForSelector('.category-btn');

        // 4. Verify theme is back to system (light in test env default)
        await expect(page.locator('body')).not.toHaveClass(/theme-dark/);

        // 5. Verify custom category still exists
        await page.click('#settings-toggle');
        await page.waitForSelector('#settings-popup', { state: 'visible' });
        await page.click('button[data-tab="categories"]');
        await expect(page.locator('.category-edit-name[value="KeepMe"]')).toBeVisible();
    });

    test('should reset categories and settings', async ({ page }) => {
         // 1. Add a custom category
        await page.click('#settings-toggle');
        await page.click('button[data-tab="categories"]');
        await page.locator('#new-category-name-settings').fill('DeleteMe');
        await page.click('#add-category-btn-settings');

        // 2. Reset all
        await page.click('button[data-tab="maintenance"]');
        await page.click('#reset-cat-settings-btn');
        await page.click('#confirm-ok-btn');

        // Page reloads
        await page.waitForURL(url => !url.href.includes('DeleteMe')); // Ensure navigation happened
        await page.waitForSelector('.category-btn');

        // 3. Verify custom category is gone
        await page.click('#settings-toggle');
        await page.waitForSelector('#settings-popup', { state: 'visible' });
        await page.click('button[data-tab="categories"]');
        await expect(page.locator('.category-edit-name[value="DeleteMe"]')).not.toBeVisible();
    });
});
