import os
import re

def generate_registry():
    animation_dir = 'src/js/animation'
    registry_file = 'src/js/animation_registry.js'

    files = [f for f in os.listdir(animation_dir) if f.endswith('.js')]
    files.sort()

    imports = []
    entries = []

    for filename in files:
        filepath = os.path.join(animation_dir, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        # Extract class name from "export default class ClassName"
        match = re.search(r'export\s+default\s+class\s+(\w+)', content)
        if match:
            class_name = match.group(1)
            module_id = filename[:-3].replace('_', '-')
            alias = class_name

            imports.append(f"import {alias} from './animation/{filename}';")
            entries.append(f"    {{ id: '{module_id}', class: {alias}, metadata: {alias}.metadata }}")

    registry_content = f"""// This file is auto-generated by scripts/generate_animation_registry.py
// Do not edit this file manually.

{chr(10).join(imports)}

export const animations = [
{(',' + chr(10)).join(entries)}
];
"""

    with open(registry_file, 'w', encoding='utf-8') as f:
        f.write(registry_content)

    print(f"Generated {registry_file} with {len(entries)} animations.")

if __name__ == "__main__":
    generate_registry()
