// This file is auto-generated by scripts/generate_animation_registry.py
// Do not edit this file manually.

import AuraCharge from './animation/aura_charge.js';
import CarDrive from './animation/car_drive.js';
import Cats from './animation/cats.js';
import Clock from './animation/clock.js';
import CoffeeDrip from './animation/coffee_drip.js';
import ContourLines from './animation/contour_lines.js';
import CrabAlien from './animation/crab_alien.js';
import DigitalRain from './animation/digital_rain.js';
import DotTyping from './animation/dot_typing.js';
import DuneFormation from './animation/dune_formation.js';
import ElasticAlert from './animation/elastic_alert.js';
import ForestFire from './animation/forest_fire.js';
import HeartBeat from './animation/heart_beat.js';
import HeroPot from './animation/hero_pot.js';
import HexagonalHud from './animation/hexagonal_hud.js';
import LeftToRight from './animation/left_to_right.js';
import LiesegangRings from './animation/liesegang_rings.js';
import MagicRibbons from './animation/magic_ribbons.js';
import MigratingBirds from './animation/migrating_birds.js';
import NewtonsCradle from './animation/newtons_cradle.js';
import NightSky from './animation/night_sky.js';
import OpenReel from './animation/open_reel.js';
import PhysarumMold from './animation/physarum_mold.js';
import PlasmaDischarge from './animation/plasma_discharge.js';
import RedCapJumper from './animation/red_cap_jumper.js';
import RepellingDigitalRain from './animation/repelling_digital_rain.js';
import RightToLeft from './animation/right_to_left.js';
import Ripple from './animation/ripple.js';
import RisingMenacing from './animation/rising_menacing.js';
import RotationalBbq from './animation/rotational_bbq.js';
import RpgGrid from './animation/rpg_grid.js';
import SandClock from './animation/sand_clock.js';
import Smoke from './animation/smoke.js';
import Spectrum from './animation/spectrum.js';
import SpotlightEvasion from './animation/spotlight_evasion.js';
import Suminagashi from './animation/suminagashi.js';
import TargetReticle from './animation/target_reticle.js';
import TestPattern from './animation/test_pattern.js';
import TetrisBuilding from './animation/tetris_building.js';
import TrophyCelebration from './animation/trophy_celebration.js';
import WindTunnel from './animation/wind_tunnel.js';
import YellowPizza from './animation/yellow_pizza.js';

export const animations = [
    { id: 'aura_charge', class: AuraCharge, metadata: AuraCharge.metadata },
    { id: 'car_drive', class: CarDrive, metadata: CarDrive.metadata },
    { id: 'cats', class: Cats, metadata: Cats.metadata },
    { id: 'clock', class: Clock, metadata: Clock.metadata },
    { id: 'coffee_drip', class: CoffeeDrip, metadata: CoffeeDrip.metadata },
    { id: 'contour_lines', class: ContourLines, metadata: ContourLines.metadata },
    { id: 'crab_alien', class: CrabAlien, metadata: CrabAlien.metadata },
    { id: 'digital_rain', class: DigitalRain, metadata: DigitalRain.metadata },
    { id: 'dot_typing', class: DotTyping, metadata: DotTyping.metadata },
    { id: 'dune_formation', class: DuneFormation, metadata: DuneFormation.metadata, devOnly: true },
    { id: 'elastic_alert', class: ElasticAlert, metadata: ElasticAlert.metadata },
    { id: 'forest_fire', class: ForestFire, metadata: ForestFire.metadata, devOnly: true },
    { id: 'heart_beat', class: HeartBeat, metadata: HeartBeat.metadata },
    { id: 'hero_pot', class: HeroPot, metadata: HeroPot.metadata },
    { id: 'hexagonal_hud', class: HexagonalHud, metadata: HexagonalHud.metadata },
    { id: 'left_to_right', class: LeftToRight, metadata: LeftToRight.metadata },
    { id: 'liesegang_rings', class: LiesegangRings, metadata: LiesegangRings.metadata, devOnly: true },
    { id: 'magic_ribbons', class: MagicRibbons, metadata: MagicRibbons.metadata },
    { id: 'migrating_birds', class: MigratingBirds, metadata: MigratingBirds.metadata },
    { id: 'newtons_cradle', class: NewtonsCradle, metadata: NewtonsCradle.metadata },
    { id: 'night_sky', class: NightSky, metadata: NightSky.metadata },
    { id: 'open_reel', class: OpenReel, metadata: OpenReel.metadata },
    { id: 'physarum_mold', class: PhysarumMold, metadata: PhysarumMold.metadata, devOnly: true },
    { id: 'plasma_discharge', class: PlasmaDischarge, metadata: PlasmaDischarge.metadata, devOnly: true },
    { id: 'red_cap_jumper', class: RedCapJumper, metadata: RedCapJumper.metadata },
    { id: 'repelling_digital_rain', class: RepellingDigitalRain, metadata: RepellingDigitalRain.metadata, devOnly: true },
    { id: 'right_to_left', class: RightToLeft, metadata: RightToLeft.metadata },
    { id: 'ripple', class: Ripple, metadata: Ripple.metadata },
    { id: 'rising_menacing', class: RisingMenacing, metadata: RisingMenacing.metadata },
    { id: 'rotational_bbq', class: RotationalBbq, metadata: RotationalBbq.metadata },
    { id: 'rpg_grid', class: RpgGrid, metadata: RpgGrid.metadata },
    { id: 'sand_clock', class: SandClock, metadata: SandClock.metadata },
    { id: 'smoke', class: Smoke, metadata: Smoke.metadata },
    { id: 'spectrum', class: Spectrum, metadata: Spectrum.metadata },
    { id: 'spotlight_evasion', class: SpotlightEvasion, metadata: SpotlightEvasion.metadata },
    { id: 'suminagashi', class: Suminagashi, metadata: Suminagashi.metadata, devOnly: true },
    { id: 'target_reticle', class: TargetReticle, metadata: TargetReticle.metadata },
    { id: 'test_pattern', class: TestPattern, metadata: TestPattern.metadata, devOnly: true },
    { id: 'tetris_building', class: TetrisBuilding, metadata: TetrisBuilding.metadata },
    { id: 'trophy_celebration', class: TrophyCelebration, metadata: TrophyCelebration.metadata },
    { id: 'wind_tunnel', class: WindTunnel, metadata: WindTunnel.metadata, devOnly: true },
    { id: 'yellow_pizza', class: YellowPizza, metadata: YellowPizza.metadata }
];
