name: 'リリース: 拡張機能パッケージの公開 (Release)'

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    uses: masanori-satake/common-workflows/.github/workflows/base-release.yml@v1
    with:
      package_source_dir: ''
      release_files: 'releases/*.zip'
