name: 'リリース: 拡張機能パッケージの公開 (Release)'

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    uses: masanori-satake/common-workflows/.github/workflows/base-release.yml@v1
    secrets: inherit
    with:
      package_source_dir: ''
      release_files: 'releases/*.zip'
      install_command: |
        echo "PUSHER_APP_ID=$PUSHER_APP_ID" >> $GITHUB_ENV
        echo "PUSHER_KEY=$PUSHER_KEY" >> $GITHUB_ENV
        echo "PUSHER_SECRET=$PUSHER_SECRET" >> $GITHUB_ENV
        echo "PUSHER_CLUSTER=$PUSHER_CLUSTER" >> $GITHUB_ENV
        npm ci
