name: "Setup and Install"

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '24'
      install-playwright:
        required: false
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup and Install Dependencies
        uses: ./.github/actions/setup-and-install
        with:
          node-version: ${{ inputs.node-version }}
          install-playwright: ${{ inputs.install-playwright }}